language: node_js
node_js:
  - '8'
branches:
  only:
  - develop
  - filtro
addons:
  sonarcloud:
    organization: davidblj-github
    token:
      secure: T0nvIPAwKzIUyOOxpAXsj1bPZLWBQRC5W2WDAOgsQ6HvrplCi1GSMpJWnidc8DnSlZhT8G5rGHRB5JD6k9KKXpZMSpqxc6+sP1GqzJbt4e/52qxJvghfeXhQn1ttlhp2u6HDPrcYwZDKvCgPddKP/hOcY6raLml/7hWiXObs8tgrgN2dXoSy0Bdc/5K4X0BP92GqY+Z1NDAznya0BuWDMyfdL3k+WVn7tx3+9Kzl8Dhnc9D6WgMb7vd8h7JTrzhYz9HGkz/yaQSP9tTOkY3AAaqMZuEanNV2bvULvGoJ6msN+MeyeqxnnzXz6g4gXdIYKPjRXPAKq+oE6xW4AKuvZyZtyH1QdTkZKR+2cSiZrLkSopbuzXA0R7jsQWaCV4KKw5HwERpr2Cg2fpRdWyBhaDg+uka0FGOOd/OayLnyytv/hOoTMbG0pAatKxARiTEoodJh3zAk9V0owLlUsDZQBnzSnWuMxh2PmfFQ7czsAMrmGpceID3ZB5fNdiYGjdREm67mrG7wE947S4Qcee/kvCt63M18TQyPmu378XWYIFlGmG8Ygi0H2uCNlpeJPgY4f76bGB6ozw4T2PTYt3AlmymcnLjR2K3y5XS2s9MnRufAktjZemcY0Gigg+Z+MNRT7ZutbamUkr09TLL1taehUQFRE6cABmsMAk3OBw3o8ao=
    branches:
      - filtro
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mongoScript.js
script:
  - npm run localTesting
  - sonar-scanner
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: mZGFdAdLsM6Fa95UFO/zn+ABN7JKa4GAtk6kXDdj4vRvQXC4ukoYBQChjE5ETcItvCc9xFtX8qZF3/TqNIXsJbEpg3ljL6vY9Atgcqx8N//rWXOXHGqEhsE1LdRLXxC5VwvBIPDCbA4hI+F01gv8OCZbOjsNBpRFiwy2nJc2afAl7vk2mvaVB4JdcA8H9pByN7AyrROpA12zD0k3w/S1MMYbdqpGe4DLE16h4HGHhJRUvZw7zpCi7Z1NeaOapSmJhY/8wlO14DC1XtK6T3huSRBp3NyBVFd0kdJRqLqO8qoUWZ3sH4FrECxRCUuNbdoWqvunx4NuLwMJUsgTJexDWJy6W6G7KnjCimQdyMfKaWeWRgnrhPbpPCWavMKxkTaWCV/xnXX/6gPLSf8KJw1OiQRNeOAvijd4x7j4tEaPtcAC8FnhPc0jpWsn2sfRfssbvAtyvOX0oGBddSAQ04Yk0POxzqbYYxU1tQE+LZoo4zDeQqqaMpJxpzLZsNrL0vPoNAqO4pBOpVTqq0Kf/oyL9+4pDciEfP+IMQMvoqGog2RVjdd/49oTOjPCCh485ShRIn+AwJhzDSbY02nJYXhut3SANGvt76eV/p4SV9OWDgqoAb/+4c7vce3BVRlR+xbNKUgUqFdIBxYFs7umLWrG6Rc3a6RleAllGtnJSCWl+P4=
  app: bolsa-de-empleos-server
  on:
    branch: filtro
