language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
# a branch naming convention should be applied (feature/*, hotfix/*, release/*)
addons:
  sonarcloud:
    organization: davidblj-github
    token: $SONAR_TOKEN
    branches:
      - develop
      - /^feature\/.*$/
services:
  - mongodb
before_script:
  - sleep 15
  - mongo scripts/mongo/indexing.js
script:
  # - npm run test
  - sonar-scanner
# travis should write a script command to index our schemas in our remote db
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: bolsa-de-empleos-server
  on:
    branch: filtro
    # branch: develop
