
### get posted jobs (page 1 to page 2)
http://localhost:3000/company/jobs?size=2&id=5ad7969f633afb26cf867c4d&offset=1
Accept: */*
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YWNlNmY0NDRhMzQ1ZjI0NmY4ZmM2ZTYiLCJuYW1lIjoiR29vZ2xlIiwidXNlcm5hbWUiOiJqYW5lIiwicm9sZSI6ImNvbXBhbnkiLCJleHAiOjE1MjQ2ODAwMzksImlhdCI6MTUyNDA3NTIzOX0.t9wOvUbvnsdw8QyziutpFO6C2355ZvFfB8YfB8iXqtA

### get posted jobs

http://localhost:3000/company/jobs?size=10
Accept: */*
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YWNlNmY0NDRhMzQ1ZjI0NmY4ZmM2ZTYiLCJuYW1lIjoiR29vZ2xlIiwidXNlcm5hbWUiOiJqYW5lIiwicm9sZSI6ImNvbXBhbnkiLCJleHAiOjE1MjQ2ODAwMzksImlhdCI6MTUyNDA3NTIzOX0.t9wOvUbvnsdw8QyziutpFO6C2355ZvFfB8YfB8iXqtA

### user check

http://localhost:3000/sign-up-check?username=jhon
Accept: */*
Content-Type: application/json

### search - get jobs to apply (page 2 to page 1)

http://localhost:3000/search/jobs?size=2&id=5ab0362dcfcbc50b93dfc43d&offset=-1
Accept: */*
Content-Type: application/json

### search - get jobs to apply (page 1 to page 2)

http://localhost:3000/search/jobs?size=2&id=5ab0362dcfcbc50b93dfc43f&offset=1
Accept: */*
Content-Type: application/json

### search - get jobs to apply (page 1)

http://localhost:3000/search/jobs?size=2
Accept: */*
Content-Type: application/json

### search - get companies

http://localhost:3000/search/companies?email=david.blj95@gmail.com&username=Uruit
Accept: */*
Content-Type: application/json

### company - get jobs

GET http://localhost:3000/company/jobs
Accept: */*
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YTdmM2MzOWEzYzM1NjQwNWQxNTQxZDMiLCJ1c2VybmFtZSI6IlVydWl0Iiwicm9sZSI6ImNvbXBhbnkiLCJleHAiOjE1MTk1NzI4NTcsImlhdCI6MTUxODk2ODA1N30.wfhfmlqtOOWmubPvxIard4EfIY7iQ18aguRknuqnahE

### user - job details

GET http://localhost:3000/jobs/5ab0362dcfcbc50b93dfc43a
Accept: */*
Content-Type: application/json

### company - job creation

POST http://localhost:3000/company/jobs
Accept: */*
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YTdmM2MzOWEzYzM1NjQwNWQxNTQxZDMiLCJ1c2VybmFtZSI6IlVydWl0Iiwicm9sZSI6ImNvbXBhbnkiLCJleHAiOjE1MTk1NzI4NTcsImlhdCI6MTUxODk2ODA1N30.wfhfmlqtOOWmubPvxIard4EfIY7iQ18aguRknuqnahE

{
  "name": "Web developer",
  "description": "Desarrollador con experiencia en JS ...",
  "to": "student",
  "languages": [
    "Ingles"
  ],
  "expiry": "2018-10-11",
  "salary": 200,
  "type": "Tiempo completo",
  "role": "desarrollador",
  "urgent": true
}

### company - session

POST http://localhost:3000/session
Accept: */*
Content-Type: application/json

{ "username": "jane", "password": "omegadjb1" }

### company - getCompany

GET http://localhost:3000/companies/5a7f3c39a3c356405d1541d3
Accept: */*
Content-Type: application/json

### company - user creation

POST http://localhost:3000/companies
Accept: */*
Content-Type: application/json

{
  "name": "Jane Doe",
  "username": "Uruit",
  "details": "We dont just build apps, we craft ...",
  "website": "https://www.uruit.com/",
  "contact": "312 724 56 24",
  "email": "JaneD@uruit.com",
  "nit": "790924937 – 6",
  "city": "Medellin",
  "sector": "Desarrollo",
  "password": "secret"
}

### candidate - getJobs

GET http://localhost:3000/candidate/jobs/
Accept: */*
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YTdmZDQ2YWIwN2MzODNjNmRhZjNjM2IiLCJ1c2VybmFtZSI6IkRvZSIsInJvbGUiOiJzdHVkZW50IiwiZXhwIjoxNTE5NDQyNjU5LCJpYXQiOjE1MTg4Mzc4NTl9.BQ_22Js63JDT5w2eMOoa0RyKvP1hOyphFLeI1X89vXk

### candidate - apply

POST http://localhost:3000/candidate/jobs/5a899d16cf01ba2200852cea
Accept: */*
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YTdmZDQ2YWIwN2MzODNjNmRhZjNjM2IiLCJ1c2VybmFtZSI6IkRvZSIsInJvbGUiOiJzdHVkZW50IiwiZXhwIjoxNTE5NDQyNjU5LCJpYXQiOjE1MTg4Mzc4NTl9.BQ_22Js63JDT5w2eMOoa0RyKvP1hOyphFLeI1X89vXk

### candidate - session

POST http://localhost:3000/session
Accept: */*
Content-Type: application/json

{ "username": "david", "password": "omegadjb1" }

### candidate - user creation

POST http://localhost:3000/candidates
Accept: */*
Content-Type: application/json

{
  "name": "John Doe",
  "username": "Doe",
  "age": 40,
  "email": "agent007@gmail.com",
  "contact": "300 310 27 03",
  "jobTitle": "spy",
  "location": "Budapest",
  "skills": [
    "math",
    "english"
  ],
  "pid": 1152209135,
  "password": "secret"
}

###
